// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weykztmdtceviegumkwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndleWt6dG1kdGNldmllZ3Vta3dpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MzM5MjAsImV4cCI6MjA3MzUwOTkyMH0.S5IVH8u7P81Rb7x1biaoVx2V5jL69w1M1qundZtRMGU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});